[tox]
envlist = py3, flake8

[testenv:py3]
basepython=python3
sitepackages=True
whitelist_externals=
  py.test
deps=
  -r{toxinidir}/requirements.txt
  pytest-cov
commands=py.test -v --cov=paddles --cov-report=term-missing {posargs:paddles}

[testenv:flake8]
basepython=python3
deps=
  flake8
commands=flake8 {posargs:paddles}
