"""Add Lab

Revision ID: 3fbf931a8608
Revises: 35aada4e1f89
Create Date: 2015-11-23 21:17:33.805171

"""

# revision identifiers, used by Alembic.
revision = '3fbf931a8608'
down_revision = '35aada4e1f89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table(
        'labs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('paused', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_name'), 'labs', ['name'], unique=False)
    op.bulk_insert(
        table,
        [{'id': 1, 'name': 'default', 'paused': False}]
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labs_name'), table_name='labs')
    op.drop_table('labs')
    ### end Alembic commands ###
