"""add timestamps to run and jobs

Revision ID: 41d8ecc1590a
Revises: 4d29434e5ce4
Create Date: 2013-10-01 11:08:45.923438

"""

# revision identifiers, used by Alembic.
revision = '41d8ecc1590a'
down_revision = '4d29434e5ce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('runs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'timestamp')
    op.drop_column('jobs', 'timestamp')
    ### end Alembic commands ###
